In [1]:
%matplotlib inline
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.signal as signal 
import scipy.fftpack
from pylab import *
from scipy import pi
import pylab
import cmath
import sys
import tensorflow as tf
#import lvm_read
print(tf.__version__)

2.5.0


## Get all using files path

In [2]:
# get want using file path
import os
from os import walk
from os.path import join

def data_path(mypath):
    filepath = []
    ae_path = []
    cu_path = []
    ae_path_container = []
    cu_path_container = []
    # 遞迴列出所有檔案的絕對路徑
    for root, dirs, files in walk(mypath):
        for f in files:
            if f.find("AEdate") >= 0: ae_path.append(f)
            elif f.find("Current") >= 0: cu_path.append(f)
#             elif f.find(".csv") >=0: equ_path = f
        ae_path.sort(key = lambda x: int(x[7:-4]))
        cu_path.sort(key = lambda x: int(x[8:-4]))
        for class_ in ae_path:
            files_path = os.path.join(root, class_)           
            ae_path_container.append(files_path)
        for class_ in cu_path:
            files_path = os.path.join(root, class_)           
            cu_path_container.append(files_path)
#         equ_path_container = equ_path
    return ae_path_container


In [3]:
et.interleave(
        lambda filepath: tf.data.from_tensor_slices(filepath).skip(23),
        cycle_length=1, num_parallel_calls=1)
# read data path
dryrun_1_path = "/media/yukun/2C167E66167E30C6/AEdata/20190313_1113_DryRun/DryRun_1/"
dryrun_1_data = data_path(dryrun_1_path)
dryrun_2_path = "/media/yukun/2C167E66167E30C6/AEdata/20200213_DryRun/water_on_fan/DryRun_2/"
dryrun_2_data = data_path(dryrun_2_path)
dryrun_3_path = "/media/yukun/2C167E66167E30C6/AEdata/20200213_DryRun/water_on_wheel/DryRun_3"
dryrun_3_data = data_path(dryrun_3_path)

row0001_1_path = "/media/yukun/2C167E66167E30C6/AEdata/20190104_1602_row0001_feed200um_1_har1/row0001_1/"
row0001_1_data = data_path(row0001_1_path)
row0001_2_path = "/media/yukun/2C167E66167E30C6/AEdata/20190104_1630_row0001_feed200um_2_har1/row0001_2/"
row0001_2_data = data_path(row0001_2_path)
row0001_3_path = "/media/yukun/2C167E66167E30C6/AEdata/20190104_1720_row0001_feed200um_3_har1/row0001_3/"
row0001_3_data = data_path(row0001_3_path)

row005_1_path = "/media/yukun/2C167E66167E30C6/AEdata/20181203_1404_row005_feed300um_1_nor1/row005_1/"
row005_1_data = data_path(row005_1_path)
row005_2_path = "/media/yukun/2C167E66167E30C6/AEdata/20181204_0900_row005_feed300um_2_nor1/row005_2/"
row005_2_data = data_path(row005_2_path)
row005_3_path = "/media/yukun/2C167E66167E30C6/AEdata/20181207_1550_row005_feed100um_3_nor1/row005_3/"
row005_3_data = data_path(row005_3_path)

row01_1_path = "/media/yukun/2C167E66167E30C6/AEdata/20181225_0234_row01_feed200um_1_sof3/row01_1/"
row01_1_data = data_path(row01_1_path)
row01_2_path = "/media/yukun/2C167E66167E30C6/AEdata/20181225_0310_row01_feed200um_2_sof3/row01_2/"
row01_2_data = data_path(row01_2_path)
row01_3_path = "/media/yukun/2C167E66167E30C6/AEdata/20181225_0350_row01_feed150um_3_sof3/row01_3/"
row01_3_data = data_path(row01_3_path)

row1_1_path = "/media/yukun/2C167E66167E30C6/AEdata/20181227_1010_row1_feed200um_1_sof2/row1_1/"
row1_1_data = data_path(row1_1_path)
row1_2_path = "/media/yukun/2C167E66167E30C6/AEdata/20181227_1102_row1_feed200um_2_sof2/row1_2/"
row1_2_data = data_path(row1_2_path)
row1_3_path = "/media/yukun/2C167E66167E30C6/AEdata/20181227_1145_row1_feed200um_3_sof2/row1_3/"
row1_3_data = data_path(row1_3_path)

row3_1_path = "/media/yukun/2C167E66167E30C6/AEdata/20190104_1355_row3_feed200um_1_sof1/row3_1/"
row3_1_data = data_path(row3_1_path)
row3_2_path = "/media/yukun/2C167E66167E30C6/AEdata/20190104_1430_row3_feed200um_2_sof1/row3_2/"
row3_2_data = data_path(row3_2_path)
row3_3_path = "/media/yukun/2C167E66167E30C6/AEdata/20190104_1510_row3_feed200um_3_sof1/row3_3/"
row3_3_data = data_path(row3_3_path)

print('dryrun_1_data :',shape(dryrun_1_data))
print('dryrun_2_data :',shape(dryrun_2_data))
print('dryrun_3_data :',shape(dryrun_3_data))

print('row0001_1_data :',shape(row0001_1_data))
print('row0001_2_data :',shape(row0001_2_data))
print('row0001_3_data :',shape(row0001_3_data))

print('row005_1_data :',shape(row005_1_data))
print('row005_2_data :',shape(row005_2_data))
print('row005_3_data :',shape(row005_3_data))

print('row01_1_data :',shape(row01_1_data))
print('row01_2_data :',shape(row01_2_data))
print('row01_3_data :',shape(row01_3_data))

print('row1_1_data :',shape(row1_1_data))
print('row1_2_data :',shape(row1_2_data))
print('row1_3_data :',shape(row1_3_data))

print('row3_1_data :',shape(row3_1_data))
print('row3_2_data :',shape(row3_2_data))
print('row3_3_data :',shape(row3_3_data))

dryrun_1_data : (57,)
dryrun_2_data : (68,)
dryrun_3_data : (306,)
row0001_1_data : (180,)
row0001_2_data : (174,)
row0001_3_data : (168,)
row005_1_data : (200,)
row005_2_data : (201,)
row005_3_data : (101,)
row01_1_data : (200,)
row01_2_data : (200,)
row01_3_data : (152,)
row1_1_data : (200,)
row1_2_data : (201,)
row1_3_data : (200,)
row3_1_data : (202,)
row3_2_data : (200,)
row3_3_data : (201,)


In [4]:
dryrun_all = np.hstack((dryrun_1_data, dryrun_2_data, dryrun_3_data))
row0001_all = np.hstack((row0001_1_data, row0001_2_data, row0001_3_data))
row005_all = np.hstack((row005_1_data, row005_2_data, row005_3_data))
row01_all = np.hstack((row01_1_data, row01_2_data, row01_3_data))
row1_all = np.hstack((row1_1_data, row1_2_data, row1_3_data))
row3_all = np.hstack((row3_1_data, row3_2_data, row3_3_data))
print('dryrun shape:  ',dryrun_all.shape)
print('row0001 shape: ',row0001_all.shape)
print('row005 shape:  ',row005_all.shape)
print('row01 shape:   ',row01_all.shape)
print('row1 shape:    ',row1_all.shape)
print('row3 shape:    ',row3_all.shape)

dryrun shape:   (431,)
row0001 shape:  (522,)
row005 shape:   (502,)
row01 shape:    (552,)
row1 shape:     (601,)
row3 shape:     (603,)


In [5]:
ae_data_path = np.hstack((dryrun_all[0:5], row0001_all[0:5], row005_all[0:5], row01_all[0:5], row1_all[0:5], row3_all[0:5]))
print('all ae data: ',shape(ae_data_path))

# get label
ae_label=[]
files = [dryrun_all[0:5], row0001_all[0:5], row005_all[0:5], row01_all[0:5], row1_all[0:5], row3_all[0:5]]
for index in range(len(files)): 
    file_dir = files[index]   
    col = np.ones([len(file_dir),])
    ae_label.extend(col*(index))
    
ae_label = np.array(ae_label)
print('all label: ',shape(ae_label))

all ae data:  (30,)
all label:  (30,)


In [6]:
# ae_val_path = np.hstack((dryrun_all[6:10], row0001_all[6:10], row005_all[6:10], row01_all[6:10], row1_all[6:10], row3_all[6:10]))
# print('all ae data: ',shape(ae_val_path))

## Preporcess data 1

In [25]:
def get_label(file):
    class_name = []
    for f in file:
        if f.find("DryRun") >=0: class_name.append(0)
        elif f.find("row0001") >=0: class_name.append(1)
        elif f.find("row005") >=0: class_name.append(2)
        elif f.find("row01") >=0: class_name.append(3)
        elif f.find("row1") >=0: class_name.append(4)
        elif f.find("row3") >=0: class_name.append(5)
    return tf.one_hot(class_name, 6, dtype=tf.int32)


def _read_py_function(filename, label):
#     labels = get_label((filename.numpy()).decode('utf-8'))
    labels = get_label(filename)
#     dt_loading = pd.read_fwf((filename.numpy()).decode('utf-8'), widths=[10])[21:5000021]
    dt_loading = pd.read_fwf(filename, widths=[10])[21:5000021]
    dt_tartype = np.array(dt_loading, dtype = np.float32)
    ae_rawdata = dt_tartype.ravel()
    ae_data = ae_rawdata - ae_rawdata.mean()
    stfts =tf.signal.stft(ae_data[:], 4096, 2048, fft_length=4096,
        window_fn=tf.signal.hann_window, pad_end=False, name=None
        )
    
    magnitude_spectrograms = tf.abs(stfts)
    mag_stft = tf.transpose(magnitude_spectrograms[:,:1024])
    mag_stft2 = tf.expand_dims(mag_stft, -1)
    return mag_stft2, labels
    

In [8]:
def _preprocess_function(ae_data, label):    
    stfts =tf.signal.stft(ae_data[:], 4096, 2048, fft_length=4096,
        window_fn=tf.signal.hann_window, pad_end=False, name=None
        )
    
    magnitude_spectrograms = tf.abs(stfts)
    mag_stft = tf.transpose(magnitude_spectrograms[:,:1024])
    mag_stft2 = tf.expand_dims(mag_stft, -1)
#     spectrograms = tf.expand_dims(log_mel_spectrograms, 3)
#     mag_stft2 = tf.reshape(mag_stft, [1024, 2440, 3])    
    return mag_stft2, label

In [15]:
# data1, label = _read_py_function(ae_data_path[0])
print(data1)
print(data1.shape)
print(label)

[ 0.00407372  0.00651471  0.00895672 ... -0.00080928  0.00163172
 -0.00813328]
(5000000,)
tf.Tensor([1 0 0 0 0 0], shape=(6,), dtype=int32)


In [25]:
mag_stft2, label2 = _preprocess_function(data1, label)
print(mag_stft2)
print(label2)

tf.Tensor(
[[[1.2195969 ]
  [2.2187958 ]
  [2.2669706 ]
  ...
  [0.7109188 ]
  [1.8340455 ]
  [1.4269618 ]]

 [[0.57142705]
  [1.089855  ]
  [1.2435471 ]
  ...
  [0.9288089 ]
  [0.6687688 ]
  [0.50131255]]

 [[0.5298968 ]
  [0.10556262]
  [0.38851884]
  ...
  [0.48943955]
  [0.7725617 ]
  [0.22039677]]

 ...

 [[0.13043717]
  [0.4092054 ]
  [0.09629249]
  ...
  [0.13149974]
  [0.53997076]
  [0.10595431]]

 [[0.49097404]
  [0.39089718]
  [0.15794124]
  ...
  [0.37124333]
  [0.18797149]
  [0.65650445]]

 [[0.6753486 ]
  [0.4377786 ]
  [0.5258601 ]
  ...
  [0.33195838]
  [0.34853783]
  [0.49736   ]]], shape=(1024, 2440, 1), dtype=float32)
tf.Tensor([1 0 0 0 0 0], shape=(6,), dtype=int32)


In [26]:
# x_data = tf.data.Dataset.from_tensor_slices(tf.constant(ae_data_path))
x_data = tf.constant(ae_data_path)
print(x_data)

# y_class = ['dryrun', 'row0001', 'row005', 'row01', 'row1', 'row3']
y_class = get_label(ae_data_path)
# y_data = tf.data.Dataset.from_tensor_slices(tf.constant(y_class))
y_data = tf.constant(y_class)
print(y_data)


tf.Tensor(
[b'/media/yukun/2C167E66167E30C6/AEdata/20190313_1113_DryRun/DryRun_1/AEdate_32.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190313_1113_DryRun/DryRun_1/AEdate_33.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190313_1113_DryRun/DryRun_1/AEdate_34.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190313_1113_DryRun/DryRun_1/AEdate_35.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190313_1113_DryRun/DryRun_1/AEdate_36.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190104_1602_row0001_feed200um_1_har1/row0001_1/AEdate_629.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190104_1602_row0001_feed200um_1_har1/row0001_1/AEdate_630.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190104_1602_row0001_feed200um_1_har1/row0001_1/AEdate_631.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190104_1602_row0001_feed200um_1_har1/row0001_1/AEdate_632.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata/20190104_1602_row0001_feed200um_1_har1/row0001_1/AEdate_633.lvm'
 b'/media/yukun/2C167E66167E30C6/AEdata

In [22]:
# dataset = tf.data.Dataset.zip({'x':x_data, 'y':y_data})
# print(dataset)
# dataset = tf.data.Dataset.from_tensor_slices((x_data, y_data))

<ZipDataset shapes: {x: (), y: ()}, types: {x: tf.string, y: tf.int32}>


In [16]:
for data in dataset.take(2):
    print(data['x'])
    print(data['y'])

tf.Tensor(b'/media/yukun/2C167E66167E30C6/AEdata/20190313_1113_DryRun/DryRun_1/AEdate_32.lvm', shape=(), dtype=string)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(b'/media/yukun/2C167E66167E30C6/AEdata/20190313_1113_DryRun/DryRun_1/AEdate_33.lvm', shape=(), dtype=string)
tf.Tensor(0, shape=(), dtype=int32)


In [27]:
dataset2 = tf.data.Dataset.from_tensor_slices(x_data, y_data)

TypeError: from_tensor_slices() takes 1 positional argument but 2 were given